TENSORBOARD_DIR: "tb/reward_0p01"
CHECKPOINT_FOLDER: "data/checkpoints/reward_0p01"
VIDEO_DIR: "../videos"
REWARD_SCALE: 0.01
NUM_CHECKPOINTS: 1
BATCHED_ENV: True
SAVE_VIDEOS_INTERVAL: 500
NUM_UPDATES: 10000
NUM_ENVIRONMENTS: 128
SIMULATOR:
  AGENTS: ['AGENT_0']
  AGENT_0:
    SENSORS: ['HEAD_RGB_SENSOR']
  HEAD_RGB_SENSOR:
    WIDTH: 128
    HEIGHT: 128
RL:
  PPO:
    num_steps: 20
    entropy_coef: 0.0025
    lr: 2.5e-4
    use_linear_lr_decay: False
  POLICY:
    action_distribution_type: "gaussian"
FORCE_BLIND_POLICY: False
