TENSORBOARD_DIR: "tb/reward_0p01"
CHECKPOINT_FOLDER: "data/checkpoints/reward_0p01"
VIDEO_DIR: "../videos"
REWARD_SCALE: 0.01
NUM_CHECKPOINTS: 0
BATCHED_ENV: True
STUB_BATCH_SIMULATOR: False
SAVE_VIDEOS_INTERVAL: 500
NUM_UPDATES: 61
NUM_ENVIRONMENTS: 256
SIMULATOR:
  AGENTS: ['AGENT_0']
  AGENT_0:
    SENSORS: ['HEAD_RGB_SENSOR']
  HEAD_RGB_SENSOR:
    WIDTH: 128
    HEIGHT: 128
RL:
  PPO:
    ppo_epoch: 1
    num_steps: 32
    entropy_coef: 0.0025
    lr: 2.5e-4
    use_linear_lr_decay: False
    max_grad_norm: 0.5
  POLICY:
    name: "PointNavBaselinePolicy"
    action_distribution_type: "gaussian"
  DDPPO:
    backbone: "se_resnet9_fixup"
FORCE_BLIND_POLICY: False
