BASE_TASK_CONFIG_PATH: configs/tasks/rearrange/reach_easy.yaml
GYM_AUTO_NAME: "ReachEasy"
TASK_CONFIG:
  TASK:
    EE_SAMPLE_FACTOR: 0.0

RL:
    REWARD_MEASURE: "rearrange_reach_reward"
    SUCCESS_MEASURE: "rearrange_reach_success"
    SUCCESS_REWARD: 1.0
    SLACK_REWARD: 0.0
    GYM_OBS_KEYS: ['joint', 'relative_resting_position']
    GYM_FIX_INFO_DICT: True
    GYM_ACTION_KEYS: ['ARM_ACTION']
    END_ON_SUCCESS: False

ENV_NAME: "RearrangeRLEnv"
