start:
    precondition: []
    state:
        robo:
            pos: 'rnd'

goal:
    - "at(goal0|0,TARGET_goal0|0)"
    - "at(goal1|1,TARGET_goal1|1)"
    - "not_holding()"
stage_goals: {}

solution: []
