init:
  - closed_cab(cab_push_point_4)
  - closed_cab(cab_push_point_5)
  - closed_cab(cab_push_point_6)
  - closed_cab(cab_push_point_7)
  - opened_fridge(fridge_push_point)

goal:
  - at(obj0_target|0,TARGET_obj0_target|0)
  - at(obj1_target|1,TARGET_obj1_target|1)
  - at(obj2_target|2,TARGET_obj2_target|2)
  - not_holding(ROBOT_0)

stage_goals:
  stage_0_5:
    - holding(obj0_target|0, ROBOT_0)
  stage_1:
    - at(obj0_target|0,TARGET_obj0_target|0, ROBOT_0)
    - not_holding(, ROBOT_0)
  stage_1_5:
    - at(obj0_target|0,TARGET_obj0_target|0, ROBOT_0)
    - holding(obj1_target|1, ROBOT_0)
  stage_2:
    - at(obj0_target|0,TARGET_obj0_target|0, ROBOT_0)
    - at(obj1_target|1,TARGET_obj1_target|1, ROBOT_0)
    - not_holding(ROBOT_0)
  stage_2_5:
    - at(obj0_target|0,TARGET_obj0_target|0, ROBOT_0)
    - at(obj1_target|1,TARGET_obj1_target|1, ROBOT_0)
    - holding(obj2_target|2, ROBOT_0)
  stage_3:
    - at(obj0_target|0,TARGET_obj0_target|0, ROBOT_0)
    - at(obj1_target|1,TARGET_obj1_target|1, ROBOT_0)
    - at(obj2_target|2,TARGET_obj2_target|2, ROBOT_0)

solution:
  - nav(obj0_target|0, ROBOT_0)
  - pick(obj0_target|0, ROBOT_0)
  - nav(TARGET_obj0_target|0, ROBOT_0)
  - place(obj0_target|0,TARGET_obj0_target|0, ROBOT_0)

  - nav(obj1_target|1, ROBOT_0)
  - pick(obj1_target|1, ROBOT_0)
  - nav(TARGET_obj1_target|1, ROBOT_0)
  - place(obj1_target|1,TARGET_obj1_target|1, ROBOT_0)

  - nav(obj2_target|2, ROBOT_0)
  - pick(obj2_target|2, ROBOT_0)
  - nav(TARGET_obj2_target|2, ROBOT_0)
  - place(obj2_target|2,TARGET_obj2_target|2, ROBOT_0)
