#types:
#  - name: art_obj
#    entity_list: ArtObjEntityList
#  - name: robot
#    entity_list: RobotEntityList
#  - name: object
#    entity_list: ObjEntityList
types:
    - robot
    - fridge
art_objs:
    cab: 0
    fridge: 1
markers:
    cab_top_left: cab_push_point_7
actions:
    - name: nav
      parameters: [obj_to]
      task: DynNavRLEnv
      task_def: "dyn_nav_task"
      precondition: []
      postcondition:
        - "at(robot,obj_to)"
    - name: pick
      parameters: [obj]
      task: RearrangePickTask-v0
      task_def: "pick"
      precondition:
          - "at(robot,obj)"
          #- "!in(obj,cab_top_left) OR opened_cab(cab_top_left)"
          #- "!in(obj,fridge) OR opened_fridge()"
      postcondition:
        - "holding(obj)"
predicates:
    - name: in
      args: [X, Y]

    - name: holding
      args: [X]
      state:
        robo:
            holding: "X"
    - name: not_holding
      state:
        robo:
            holding: 'NONE'
    - name: at
      args: [robot,Y]
      state:
        robo:
            pos: Y
    - name: at
      args: [X,Y]
      state:
          obj_states:
              X: Y
    - name: closed_fridge
      state:
          art_states:
              1: [0,0]
    - name: opened_fridge
      state:
          art_states:
              1: "ArtLinkBetween(1, 2.0, 2.1, 0.6)"
    - name: opened_cab
      args: [cab_id]
      state:
        art_states:
          # The final number is the success distance threshold, not used for sampling
          0: "ArtLinkFromMarkerBetween('cab_id', 0.5, 0.5001, 1.0, sim, name_to_id, 0.15)"
    - name: opened_cab
      # Open cab, but move some objects with it. This is not an ideal solution,
      # but currently there is no way to tell which objects are inside of a
      # receptacle.
      args: [cab_id,catch_ids]
      state:
        art_states:
          0: "ArtLinkFromMarkerBetween('cab_id', 0.5, 0.5001, 1.0, sim, name_to_id, 0.15)"
        catch_ids: catch_ids
    - name: closed_cab
      args: [cab_id]
      state:
        art_states:
          0: "ArtLinkFromMarkerBetween('cab_id', 0.0, 0.01, 1.0, sim, name_to_id, 0.1)"
