#types:
#  - name: art_obj
#    entity_list: ArtObjEntityList
#  - name: robot
#    entity_list: RobotEntityList
#  - name: object
#    entity_list: ObjEntityList
types:
    - robot
    - fridge
art_objs:
    cab: 0
    fridge: 1
markers:
    cab_top_left: cab_push_point_7
actions:
    - name: nav
      parameters: [obj_to]
      task: DynNavRLEnv
      task_def: "dyn_nav_task"
      precondition: []
      postcondition:
        - "at(robot,obj_to)"
    - name: pick
      parameters: [obj]
      task: RearrangePickTask-v0
      task_def: "pick"
      precondition:
          - "at(robot,obj)"
          #- "!in(obj,cab_top_left) OR opened_cab(cab_top_left)"
          #- "!in(obj,fridge) OR opened_fridge()"
      postcondition:
        - "holding(obj)"
predicates:
    - name: in
      args: [X, Y]

    - name: holding
      args: [X]
      state:
        robo:
            holding: "X"
    - name: not_holding
      state:
        robo:
            holding: 'NONE'
    - name: at
      args: [robot,Y]
      state:
        robo:
            pos: Y
    - name: at
      args: [X,Y]
      state:
          obj_states:
              X: Y
