# @package habitat.task.measurements.top_down_map


type : TopDownMap
max_episode_steps: 1000
map_padding: 3
map_resolution: 1024
draw_source: True
draw_border: True
draw_shortest_path: True

fog_of_war:
  draw: True
  visibility_dist: 5.0
  fov: 90

draw_view_points: True
draw_goal_positions: True
draw_goal_aabbs: True
