# @package habitat.dataset
defaults:
  - /habitat/dataset: dataset_config_schema
  - _self_

type: ObjectNav-v1
split: train
data_path: data/datasets/objectnav/ai2thor/procthor/v0.0.8_6_cat/{split}/{split}.json.gz
scenes_dir: data/scene_datasets/ai2thor/v0.0.8/configs/scenes/ProcTHOR
