# @package habitat.dataset

defaults:
  - /habitat/dataset: dataset_config_schema
  - _self_

type: PointNav-v1
split: train
data_path: data/datasets/pointnav/floorplanner/v1/{split}/{split}.json.gz
scenes_dir: data/scene_datasets/floorplanner/v1/configs/scenes
