ENVIRONMENT:
    MAX_EPISODE_STEPS: 20
DATASET:
    TYPE: RearrangeDataset-v0
    SPLIT: train
    DATA_PATH: data/ep_datasets/default.json.gz
    SCENES_DIR: "data/replica_cad/"
TASK:
    TYPE: RearrangeReachTask-v0
    RENDER_TARGET: True
    EE_SAMPLE_FACTOR: 0.0

    JOINT_SENSOR:
        TYPE: "JointSensor"
        DIMENSIONALITY: 7
    RELATIVE_RESTING_POS_SENSOR:
        TYPE: "RelativeRestingPositionSensor"
    RESTING_POS_SENSOR:
        TYPE: "RestingPositionSensor"
    END_EFFECTOR_SENSOR:
        TYPE: "EEPositionSensor"
    SENSORS: ["JOINT_SENSOR", "RELATIVE_RESTING_POS_SENSOR"]

    END_EFFECTOR_TO_REST_DISTANCE:
        TYPE: "EndEffectorToRestDistance"
    REARRANGE_REACH_REWARD:
        TYPE: "RearrangeReachReward"
        SCALE: 1.0
        DIFF_REWARD: True
        SPARSE_REWARD: False
    REARRANGE_REACH_SUCCESS:
        TYPE: "RearrangeReachSuccess"
        SUCC_THRESH: 0.1
    ANY_REACH_SUCCESS:
        TYPE: "AnyReachSuccess"
    MEASUREMENTS:
        - "END_EFFECTOR_TO_REST_DISTANCE"
        - "REARRANGE_REACH_SUCCESS"
        - "REARRANGE_REACH_REWARD"
        - "ANY_REACH_SUCCESS"
    ACTIONS:
        ARM_ACTION:
            TYPE: "ArmAction"
            ARM_CONTROLLER: "ArmRelPosAction"
            ARM_JOINT_DIMENSIONALITY: 7
            GRIP_CONTROLLER: null
            EE_CTRL_LIM: 0.06
            GRASP_THRESH_DIST: 0.15
            DELTA_POS_LIMIT: 0.025
            RENDER_EE_TARGET: True
    POSSIBLE_ACTIONS:
        - ARM_ACTION

SIMULATOR:
    ACTION_SPACE_CONFIG: v0
    RENDER_CAMERA_OFFSET: [1.3, 1.3, -0.0]
    RENDER_CAMERA_LOOKAT: [0, 0.4, 0]
    AGENTS: ['AGENT_0']
    AGENT_0:
        HEIGHT: 1.5
        IS_SET_START_STATE: True
        RADIUS: 0.1
        SENSORS: ['HEAD_RGB_SENSOR']
        START_POSITION: [0.0, 0.0, 2.0]
        START_ROTATION: [0.0, 0.0, 0.0, 1.0]
    HEAD_RGB_SENSOR:
        WIDTH: 128
        HEIGHT: 128
    THIRD_RGB_SENSOR:
        WIDTH: 512
        HEIGHT: 512

    # Agent setup
    ARM_REST: [0.6, 0.0, 0.9]
    CTRL_FREQ: 120.0
    AC_FREQ_RATIO: 8
    ROBOT_URDF: ./data/robots/hab_fetch/robots/hab_fetch.urdf
    ROBOT_TYPE: "FetchRobot"
    EE_LINK_NAME: null
    IK_ARM_URDF: null
    FORWARD_STEP_SIZE: 0.25
    LOAD_OBJS: False

    # Grasping
    HOLD_THRESH: 0.09
    GRASP_IMPULSE: 1000.0

    DEFAULT_AGENT_ID: 0
    HABITAT_SIM_V0:
        ALLOW_SLIDING: True
        ENABLE_PHYSICS: True
        GPU_DEVICE_ID: 0
        GPU_GPU: False
        PHYSICS_CONFIG_FILE: ./data/default.physics_config.json
    SEED: 100
    SEMANTIC_SENSOR:
        HEIGHT: 480
        HFOV: 90
        ORIENTATION: [0.0, 0.0, 0.0]
        POSITION: [0, 1.25, 0]
        TYPE: HabitatSimSemanticSensor
        WIDTH: 640
    TILT_ANGLE: 15
    TURN_ANGLE: 10
    TYPE: RearrangeSim-v0
